name: Push CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        fetch-depth: 0
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Build with Gradle
      id: build
      env:
        KEYSTORE_PASSWORD: test666
        KEY_ALIAS: test666
        KEY_PASSWORD: test666
      run: |
        echo 'org.gradle.jvmargs=-Xmx3072m' >> gradle.properties
        chmod +x gradlew
        ./gradlew :app:assembleRelease
        echo "APK_PATH=$(find app/build/outputs/apk/release -name "*.apk" | head -1)" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      if: steps.build.outputs.status == 'success' && !cancelled()
      with:
        name: app-release
        path: ${{ env.APK_PATH }}
    
    - name: Post to Telegram
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      env:
        FILE: ${{ env.APK_PATH }}
        COMMIT_MESSAGE: |+
          New push to github!
          ```
          ${{ github.event.head_commit.message }}
          ```by `${{ github.event.head_commit.author.name }}`
          See commit detail [here](${{ github.event.head_commit.url }})
          Snapshot apk is attached
      run: |
        # 转义消息内容
        ESCAPED_MESSAGE=$(echo '${{ env.COMMIT_MESSAGE }}' | python3 -c 'import json, sys; print(json.dumps(sys.stdin.read()).strip("\""))')
        
        # 发送到Telegram
        curl -F chat_id="${{ secrets.TELEGRAM_TO }}" \
             -F document=@"$FILE" \
             -F caption="$COMMIT_MESSAGE" \
             -F parse_mode="Markdown" \
             "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument"
